---
# RedHat related OSs
- name: Yum install {{ item }}
  action: yum pkg={{ item }} state=installed
  when: "ansible_os_family == 'RedHat'"
  with_items:
  - wget
  - tar
  - gzip
  - java-1.8.0-openjdk

- name: Ubuntu 14 install software-properties-common
  apt: name=software-properties-common
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14"

- name: Ubuntu 14 install OpenJDK PPA repo
  apt_repository: repo='ppa:openjdk-r/ppa'
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14"

# Debian related OSs
- name: Apt install {{ item }}
  action: apt pkg={{ item }} state=installed update_cache=yes cache_valid_time=604800
  when: "ansible_os_family == 'Debian'"
  with_items:
  - wget
  - tar
  - gzip
  - openjdk-8-jre

# download only in the ansible master node
- local_action: get_url url={{ hadoop_mirrors|random }}/hadoop-{{ hadoop_version }}.tar.gz dest={{ hadoop_download_path }}/hadoop-{{ hadoop_version }}.tar.gz force=no
  become: no
  register: result
  until: result|success
  retries: 5
  delay: 2
  when: hadoop_type_of_node == 'master'

# other nodes wait for it
- local_action: wait_for path={{ hadoop_download_path }}//hadoop-{{ hadoop_version }}.tar.gz
  become: no
  when: hadoop_type_of_node != 'master'

- copy: src={{ hadoop_download_path}}/hadoop-{{ hadoop_version }}.tar.gz dest=/opt/hadoop-{{ hadoop_version }}.tar.gz force=no

- unarchive: src=/opt/hadoop-{{ hadoop_version }}.tar.gz dest=/opt creates=/opt/hadoop-{{ hadoop_version }} copy=no

- file: dest={{ hadoop_home }} src=/opt/hadoop-{{ hadoop_version }} state=link

- file: dest=/opt/hadoop src={{ hadoop_home }} state=link

- name: Find path for Java executable
  shell: 'find -L /usr/lib/jvm -name java -executable | head -n 1 | xargs dirname'
  register: java_register_env

- lineinfile: dest={{ hadoop_home }}/etc/hadoop/hadoop-env.sh regexp="^export JAVA_HOME=" line="export JAVA_HOME={{ java_register_env.stdout }}/../.."
